site_name: Defra Software Development Standards
site_url: https://defra.github.io/software-development-standards
theme: 
  name: material
  custom_dir: overrides
  logo: img/brand.png
  favicon: img/brand.ico
  palette:
    primary: custom
  font:
    text: 'Arial'
    code: 'Roboto Mono'
extra_css:
  - stylesheets/extra.css
repo_url: https://github.com/DEFRA/software-development-standards
remote_branch: gh-pages
nav:
  - Home: README.md
  - Principles:
    - Overview: principles/README.md
    - Coding principles: principles/coding_principles.md
    - Security principles: principles/security_principles.md
  - Standards:
    - Coding standards:
      - Common coding standards: standards/common_coding_standards.md
      - Continuous integration standards: standards/continuous_integration.md
      - C# coding standards: standards/csharp_coding_standards.md
      - Development languages: standards/development_language_standards.md
      - JavaScript standards: standards/javascript_standards.md
      - Logging standards: standards/logging_standards.md
      - Mobile application standards: standards/mobile_app_standards.md
      - .NET standards: standards/net_standards.md
      - Node.js standards: standards/node_standards.md
      - Python coding standards: standards/python_coding_standards.md
      - Quality assurance and test standards: standards/quality_assurance_standards.md
      - Security standards: standards/security_standards.md
      - UiPath standards: standards/uipath_standards.md
      - Version control standards: standards/version_control_standards.md
    - Packaging and deployment standards:
      - Container standards: standards/container_standards.md
      - Deployment standards: standards/deployment_standards.md
      - Kubernetes standards: standards/kubernetes_standards.md
    - Database standards:
      - PL/SQL coding standards: standards/plsql_coding_standards.md
      - TSQL and SQL Server database standards: standards/tsql_and_sqldb_standards.md
    - Documentation standards:
      - README standards: standards/readme_standards.md
    - Standards for non-strategic technologies:
      - Java coding standards: standards/java_coding_standards.md
      - Ruby coding standards: standards/ruby_coding_standards.md
  - Processes and guides:
    - Processes:
      - Credential exposure: processes/credential_exposure.md
      - GitHub access: processes/github_access.md
      - Pull requests: processes/pull_requests.md
      - Resolving GitHub security alerts: processes/github_security_alerts.md
    - Guides:
      - General guidance: guides/README.md
      - Choosing between a mono repo and a multi repo: guides/mono_or_multi_repo.md
      - Choosing packages: guides/choosing_packages.md
      - Developer workflows: guides/developer_workflows.md
      - Docker guidance: guides/docker_guidance.md
      - Java auto-format with Eclipse: guides/java_auto_format_eclipse.md
      - Kubernetes: guides/kubernetes.md
      - Managing application credentials: guides/application_credentials.md
      - Mobile application guidance: guides/mobile_app_guidance.md
      - New starters: guides/new_starters.md
      - Opening existing private code: guides/opening_private_code.md
      - PL/SQL auto-format with TOAD: guides/plsql_auto_format_toad.md
      - SQL Prompt: guides/sql_prompt_tool.md
      - Shared libraries: guides/shared_libraries.md
      - Style guide for standards: guides/style_guide_for_standards.md
      - Training: guides/training.md
      - Using AWS session manager: guides/aws_session_manager.md
      - Using devices with privileged access: guides/privileged_devices.md
      - Version control guidance: guides/version_control_guidance.md
  - Contributing: CONTRIBUTING.md
